language: php
php:
  - 5.6
  - 7.0
  - hhvm
before_script:
  - composer install --dev

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml

after_script:
  - php vendor/bin/coveralls
